README.md, package-lock.json, package.json, src/routes/Header.svelte, src/routes/audio/Audio.svelte, src/routes/spotify/+page.svelte, src/routes/spotify/Audio.svelte
Spotify Web Playback audio component with custom control components.
With:
- Manual Spotify access token
- Development docs
- Audio improvements
=> Spotify Web Playback Audio

README.md, src/routes/spotify/+page.svelte, src/routes/spotify/Audio.svelte, src/routes/spotify/Login.svelte, src/routes/spotify/Title.svelte, src/routes/spotify/api.test.ts, src/routes/spotify/api.ts, src/routes/spotify/auth.ts, src/routes/spotify/callback/+page.svelte, src/routes/spotify/track/+page.svelte
Spotify authorization code with PKCE.
With:
- Docs
- Log in / out button
=> Spotify Auth

src/routes/audio/PlaySkip.svelte, src/routes/spotify/+page.svelte, src/routes/spotify/Audio.svelte
With:
- Send ended updates
- Add effect to ended that plays next track
=> Spotify ended update and auto play next

src/lib/types/music.ts, src/routes/spotify/Title.svelte, src/routes/spotify/api.test.ts, src/routes/spotify/api.ts, src/routes/spotify/jukebox/+page.svelte
Prototype page that progressively loads 100 albums for a jukebox
- Playlist and PlaylistTracks types
- Track to album helper
- Playlist fingerprint cache
=> Multi-album Jukebox

src/routes/spotify/jukebox/+page.svelte, src/routes/spotify/jukebox/playlist.svelte.ts
- Playlist module
- Get and chunk albums
- Enqueue and skip tracks
- State for queue, shuffle, history
- UX improvements
- Click for dialog to confirm track
- Auto dialog for enqueued tracks
- Layout improvements
- Queue, shuffle and history sidebar lists
- Scroll and overflow tweaks
=> Jukebox playlist and queue

.env.example, .github/workflows/ci.yml, package-lock.json, package.json, src/lib/spotify/auth.ts, src/routes/audio/+page.ts, src/routes/spotify/+page.ts, src/routes/spotify/callback/+page.ts, src/routes/spotify/jukebox/+page.ts, svelte.config.js
- Configure app for static adapter
- Add action to setup node, build site on PR, upload to pages on `main`
=> Static site and build for GitHub pages

.prettierrc, package-lock.json, package.json, src/lib/href.test.ts, src/lib/href.ts, src/lib/spotify/auth.ts, src/routes/+page.svelte, src/routes/Header.svelte, src/routes/about/+page.svelte, src/routes/audio/+page.svelte, src/routes/spotify/jukebox/+page.svelte
Support running under https://nzoschke.github.io/jukelab/ or any other sub path defined by PUBLIC_ORIGIN.
=> Relative paths for GitHub Pages

src/routes/spotify/jukebox/+page.svelte, src/routes/spotify/jukebox/playlist.svelte.ts, src/routes/spotify/jukebox/select.svelte.ts
- Change pages via keys
- Select album and track via keys
=> Physical and touch keys

src/routes/spotify/jukebox/+page.svelte, src/routes/spotify/jukebox/playlist.svelte.ts, src/routes/spotify/jukebox/storage.svelte.ts
- Get playlist src from hash or local storage
- List playlists in menu
- Custom playlist form
Updates #33
=> Custom playlists

src/routes/spotify/Audio.svelte, src/routes/spotify/jukebox/+page.svelte, src/routes/spotify/jukebox/playlist.svelte.ts, src/routes/spotify/jukebox/storage.svelte.ts
Save the queue and history to local storage to resume on page reload
=> Queue and history persistance

package-lock.json, package.json, src/routes/spotify/Audio.svelte, src/routes/spotify/jukebox/+page.svelte
=> No sleep that is enabled when playback starts

src/routes/spotify/Menu.svelte, src/routes/spotify/Queue.svelte, src/routes/spotify/Sleep.svelte.ts, src/routes/spotify/desktop/+page.svelte, src/routes/spotify/keypad/+page.svelte, src/routes/spotify/playlist.svelte.ts, src/routes/spotify/storage.ts
- Add rearrange and clear buttons to queue, shuffle and history lists
- Extract menu component
- Simplify playlist loading
=> Desktop skin improvements

src/routes/audio/Broadcast.svelte, src/routes/spotify/remote/+page.svelte
=> Remote mobile ui improvements

src/lib/supabase/auth.ts, src/routes/spotify/playlist.svelte.ts
TODO: Test refresh after 1 hour
=> Refresh Spotify Token

src/routes/audio/Play.svelte, src/routes/spotify/Audio.svelte, src/routes/spotify/desktop/+page.svelte, src/routes/spotify/log.svelte.ts, tailwind.config.ts
- Log token refresh
- Theme and color changes
- Carousel pagination and scroll improvements
=> Desktop skin polish

src/routes/spotify/Audio.svelte
Add additional logging to help review playback errors
=> Spotify logging

src/routes/spotify/Menu.svelte, src/routes/spotify/desktop/+page.svelte, src/routes/spotify/log.svelte.ts
Add a button to toggle full screen mode, which hides nav and footer in landscape orientation. Turn to portrait to show footer and toggle off.
=> Full screen kiosk

package-lock.json, package.json, src/routes/spotify/Menu.svelte, src/routes/spotify/vinyl/+page.svelte
=> Mobile skin foundation

src/lib/spotify/api.test.ts, src/lib/spotify/api.ts, src/lib/storage.ts, src/routes/spotify/playlist.svelte.ts
- Load more than 100 albums
- Clear queue, history and shuffle on playlist change
=> Playlist fixes

src/routes/spotify/desktop/Attract.svelte
=> Attract screen tweaks

src/routes/spotify/desktop/+page.svelte
- Hidden button to exit full screen
- Attract screen resets on touch events
=> Full screen and attract screen fixes

src/routes/spotify/desktop/+page.svelte, src/routes/spotify/playlist.svelte.ts
Single column, show track number
=> Last min tweaks

src/routes/spotify/desktop/+page.svelte
Tweaking colors/icons/positions a bit:
=> Desktop ui tweaks

src/lib/array.ts, src/routes/spotify/desktop/Attract.svelte, src/routes/spotify/keypad/+page.svelte, src/routes/spotify/playlist.svelte.ts
And make sure albums don't overlap the carousels.
=> Shuffle albums on attract screen

src/lib/shared/snow.svelte, src/lib/spotify/api.ts, src/lib/storage.ts, src/routes/spotify/Menu.svelte, src/routes/spotify/desktop/+page.svelte, src/routes/spotify/desktop/Attract.svelte, src/routes/spotify/desktop/store.ts, static/snow.svg
Fiddling around... Let me see if I can get a better snow effect/figure out how to make it less invisible
=> Holiday mode

src/routes/spotify/desktop/Attract.svelte, src/routes/spotify/desktop/attract/DVD.svelte, src/routes/spotify/desktop/attract/Standard.svelte, src/routes/spotify/desktop/attract/Vinyl.svelte
Allow users to toggle the attention screen, adding vinyl and bouncy dvd modes:
Not sold on anything here, open for ideas/input!
=> New attention screens

package-lock.json, package.json, src/lib/photobooth.ts, src/routes/spotify/Menu.svelte, src/routes/spotify/desktop/+page.svelte, src/routes/spotify/desktop/PlayDialog.svelte, src/routes/spotify/desktop/attract/DVD.svelte, src/routes/spotify/desktop/attract/Standard.svelte, src/routes/spotify/desktop/attract/Vinyl.svelte, src/routes/spotify/playlist.svelte.ts
v1 with static album on the top just to get it started
will push a variation using tensorflow to replace the background for the album cover
=> Photobooth!
